### ISSUE TITLE
Save sequencer sample selection

### ISSUE THREAD

**Issue by khaki32** [brandongregoryscott/beets#147]
Save the selected sample or samples for the sequencer. So if you select a sample in a sequencer section and then close and reopen a sequencer section, you don't have to select that sample again.

Love the project by the way.

**Comment by brandongregoryscott** [comment]
Thanks @khaki32!

I've definitely thought about this as a workflow improvement, too. I'm a little hesitant to implement it as the default behavior, though - I could see people wanting the Sequencer to open up as a "clean slate" too, so maybe it would be nice to have a user setting to toggle this on/off.

As far as _how_ it would work, would you want it to save the selected sample(s) at the Track level or on a Track Section basis?

**Comment by khaki32** [comment]
> I'm a little hesitant to implement it as the default behavior, though - I could see people wanting the Sequencer to open up as a "clean slate" too, so maybe it would be nice to have a user setting to toggle this on/off.

I agree, this would be good as customizable behavior. As far as the default setting goes, there could be an "X" button next to the sample dropdown to quickly clear the selected samples. As a nice comprise.

> As far as how it would work, would you want it to save the selected sample(s) at the Track level or on a Track Section basis?

For me definitely at the track level, but that's just personal preference.

**Comment by brandongregoryscott** [comment]
Going to start hacking on this - I can probably get out a version that stores the selected samples in local storage as a hold-over (will remember sample selections for a track while in the same browser until local storage/app data has been cleared), but longer term I'd love to build out some of the infrastructure for a generic user settings table and wire this up to it! (#40)

**Comment by brandongregoryscott** [comment]
This should be out now - let me know if you run into any issues!

**Comment by khaki32** [comment]
Cool! Works and looks great.

**Comment by khaki32** [comment]
Just wanna comment that it's really nice that you did this with local storage! Saves it even after a few days.

**Comment by brandongregoryscott** [comment]
> Just wanna comment that it's really nice that you did this with local storage! Saves it even after a few days.

Glad to hear! I was thinking local storage should be pretty solid for something like this - the other implementation I was tossing around in my head is persisting records in a linking table in the database, but it seemed like too much work for very little payoff vs. something so simple to wire up with local storage!
