### ISSUE TITLE
Add table of contents and max width to Help pages

### ISSUE THREAD

**Issue by khaki32** [brandongregoryscott/beets#164]
Adding a tables of content to page makes it easier to quickly find what you're looking for. It also gives you a quick representation of what's on the page.

Adding max width to the text makes it easier to read in fullscreen view (as an actual page and not a pop-up), as the lines wrap a lot earlier.

**Comment by brandongregoryscott** [comment]
Table of contents would go a long way! Thanks for the feedback - this should be quick to tidy up.
