### ISSUE TITLE
Add preview button on FileCard

### ISSUE THREAD

**Issue by brandongregoryscott** [brandongregoryscott/beets#174]
Similar to the preview button that is present in the `FileSelectMenu`, add a `PlayButton` that plays the sample  on the `FileCard` component:

![image](https://user-images.githubusercontent.com/11774799/163892983-894be547-73b8-4a81-a192-9dbe5d90fa1b.png)

See implementation in [`FileSelectMenuItem`](https://github.com/brandongregoryscott/beets/blob/main/src/components/file-select-menu-item.tsx) for reference:

https://github.com/brandongregoryscott/beets/blob/91a07e9264e86f1f026cb97e0010b4b55f5bd810/src/components/file-select-menu-item.tsx#L67-L76

**Comment by HeyKos** [comment]
@brandongregoryscott I'll give this one a shot if you like.

**Comment by brandongregoryscott** [comment]
Go for it @HeyKos!

**Comment by HeyKos** [comment]
@brandongregoryscott Do you have a preference where the play button goes? This is where I have it currently 
<img width="327" alt="Screen Shot 2022-10-11 at 8 50 39 PM" src="https://user-images.githubusercontent.com/5178698/195224159-80b24152-e857-4554-bbca-c126dd50af1c.png">

**Comment by brandongregoryscott** [comment]
I think that makes sense!

**Comment by HeyKos** [comment]
@brandongregoryscott I have it done, but I think some of the duplicated code can possibly be combined into a shareable component if you think it is work the effort. Currently in order to function you need a `PlayButton` component, and audio `component` (with ref), a `useBoolean` hook reference to maintain state and a play click handler. I think these could all be packaged up nicely. I can either create a separate issue, or prove it out in a PR for this issue. Whatever you prefer.

**Comment by HeyKos** [comment]
@brandongregoryscott I'll add it in this issue, and update the existing uses of PlayButton to use the PlayAudio button. That way I'll have a good sampling of what props need to be exposed. You might as well give me #175 too, since after this it'll be super trivial.

**Comment by brandongregoryscott** [comment]
It won't let me assign it (it probably needs you to be subscribed to the issue w/ a comment first) but go for it!

**Comment by HeyKos** [comment]
@brandongregoryscott I have run into a bit of a pickle with the PlayAudioButton component. There are a few uses of play button where the `useToneAudio` hook is taking charge of the actual playback state. Do you have any preference on how we could/should handle those scenarios? Currently `useToneAudio` is used in `piano-roll.tsx`, `sequencer.tsx` and `song-controls.tsx`.

**Comment by brandongregoryscott** [comment]
>update the existing uses of PlayButton to use the PlayAudio button.

> There are a few uses of play button where the `useToneAudio` hook is taking charge of the actual playback state. 

Err, maybe I missed this the first time around. 

I think we can keep the existing `PlayButton` usages in `piano-roll.tsx`, `sequencer.tsx` and `song-controls.tsx` since they interact w/ Tone directly (and no `audioRef` is required). Let's swap the existing usage in `FileSelectMenuItem` which has the audio ref, but keep the rest the same. Maybe we can name the new component `PlayPreviewButton` to differentiate it from the more generic `PlayButton`.

**Comment by HeyKos** [comment]
Works for me. Thanks!

**Comment by brandongregoryscott** [comment]
Completed via #291
