### ISSUE TITLE
Add keyboard/combo shortcut documentation

### ISSUE THREAD

**Issue by brandongregoryscott** [brandongregoryscott/beets#181]
While there's only a few keyboard shortcuts available right now, the list will grow as the app evolves.

Current keyboard shortcuts:

`Ctrl+S or ⌘S` - Saves the Project
`Ctrl+D or ⌘D` - Duplicates the currently selected Track Section(s)
`Shift + Click` - Extends step selection/loop range when clicking on the `TrackTime` component, or enables selection of multiple Track Sections

**Comment by khaki32** [comment]
Do you have any plans to let the commands also be activated with `Ctrl`? For example, `Ctrl+S` as well as `⌘+S` to save the project.

**Comment by brandongregoryscott** [comment]
Ah, yeah - just an oversight on my part since I'm on mac. It shouldn't be too hard to wire up into the existing `useHotkeys` hook calls:

https://github.com/brandongregoryscott/beets/blob/76d60084f44d08d329e7cb820908d3b5a46ed727/src/components/workstation/file-tab.tsx#L131-L138

https://github.com/brandongregoryscott/beets/blob/76d60084f44d08d329e7cb820908d3b5a46ed727/src/components/workstation/edit-tab.tsx#L29

**Comment by khaki32** [comment]
I'd like to do this - when I actually get it working locally.

**Comment by brandongregoryscott** [comment]
Fixed with #201
