### ISSUE TITLE
Chore: Refactor ConditionalTooltip component with isShown prop

### ISSUE THREAD

**Issue by brandongregoryscott** [brandongregoryscott/beets#286]
Based on the documentation on the Evergreen site for `Tooltip`, refactor the `ConditionalTooltip` to leverage the `isShown` prop (passing `false` or `undefined` depending on the state) instead of conditionally rendering children or the Tooltip.

https://evergreen.segment.com/components/tooltip#conditionally_show_tooltip

**Comment by HeyKos** [comment]
@brandongregoryscott can you assign me this one?
