### ISSUE TITLE
Create Instrument from InstrumentsPage

### ISSUE THREAD

**Issue by brandongregoryscott** [brandongregoryscott/beets#60]
Add a button to pull up the `InstrumentSettingsDialog` to create a new `Instrument` from `/library/instruments`.

**Comment by khaki32** [comment]
Would be nice to see this! I think the InstrumentsPage deserves some love.

**Comment by brandongregoryscott** [comment]
Released in [v1.17.0](https://github.com/brandongregoryscott/beets/releases/tag/v1.17.0)
